name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache the kernel
      id: cache-kernel
      uses: actions/cache@v4
      with:
        path: linux-6.8.9
        key: linux-6.8.9

    - name: Download
      if: steps.cache-kernel.outputs.cache-hit != 'true'
      run: wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.8.9.tar.xz

    - name: Install the kernel source
      if: steps.cache-kernel.outputs.cache-hit != 'true'
      run: |
        xz -cd linux-6.8.9.tar.xz | tar xvf -
        cd linux-6.8.9
        make mrproper

    - name: Install libelf-dev
      if: steps.cache-kernel.outputs.cache-hit != 'true'
      run: sudo apt-get install -y libelf-dev

    - name: Configure the kernel
      if: steps.cache-kernel.outputs.cache-hit != 'true'
      run: |
        cd linux-6.8.9
        make defconfig

    - name: Compile the kernel
      if: steps.cache-kernel.outputs.cache-hit != 'true'
      run: |
        cd linux-6.8.9
        make

    - name: Build root filesystem
      run: |
        mkdir -p iso/boot

    - name: Make a GRUB bootable CD-ROM
      run: |
        sudo apt-get install -y mtools
        mkdir -p iso/boot/grub
        cat << EOF > iso/boot/grub/grub.cfg
        set default=0
        set timeout=0
        menuentry 'Linux' {
            linux /boot/vmlinuz console=ttyS0 console=tty0 ignore_loglevel
            initrd /boot/initramfs.cpio.gz
        }
        EOF
        grub-mkrescue -o grub.iso iso

    - name: Archive the ISO
      uses: actions/upload-artifact@v4
      with:
        name: grub.iso
        path: grub.iso
